# Generated by Django 3.2.7 on 2021-09-17 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('cover_image', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('genre', models.CharField(choices=[('DRAMA', 'Drama'), ('COMEDY', 'Comedy'), ('SF', 'Sf'), ('HOROR', 'Horor')], default='DRAMA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.BooleanField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
